---
title: Guard cell size and pore aperture influence stomatal closure kinetics
format:
  pdf:
    keep-tex: true  
    toc: false
author:
  - name: "Christopher D. Muir$^{1,2*}$"
    orcid: 0000-0003-2555-3878
  - name: "Wei Shen Lim$^{1}$"
affiliations: false
number-sections: false
header-includes: |
  \usepackage{hyperref}
  \addtokomafont{disposition}{\rmfamily}
  \usepackage{siunitx}
  \newcommand{\Aamphi}{$A_{\mathrm{amphi}}$}
  \newcommand{\Ahypo}{$A_{\mathrm{hypo}}$}
  \newcommand{\agcurve}{$A \textendash g_\text{sw}$}
  \newcommand{\ca}{$C_\mathrm{a}$}
  \newcommand{\caequals}[1]{$C_\mathrm{a} = \qty{#1}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\cabetween}[2]{#1 < $C_\mathrm{a} < \qty{#2}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\gmax}{$g_\text{max}$}
  \newcommand{\gmaxratio}{$g_\text{max,ratio}$}
  \newcommand{\gmaxshade}{$g_\text{max,shade}$}
  \newcommand{\gmaxsun}{$g_\text{max,sun}$}
  \newcommand{\gsw}{$g_\text{sw}$}
  \newcommand{\loggsw}{$\log(g_\text{sw})$}
  \newcommand{\logA}{$\log(A)$}
  \newcommand{\ppfd}{$\mathrm{PPFD}$}
  \newcommand{\ppfdequals}[1]{$\mathrm{PPFD} = \qty{#1}{\micro\mol\raiseto{-2}\meter\raiseto{-1}\second}$}
  \newcommand{\ppfdqty}[1]{$\qty{#1}{\micro\mol\raiseto{-2}\meter\raiseto{-1}\second}$}
  \newcommand{\rh}{$\mathrm{RH}$}
  \newcommand{\rhequals}[1]{$\mathrm{RH} = #1\%$}
  \newcommand{\tleafequals}[1]{$T_\mathrm{leaf} = \qty{#1}{\degreeCelsius}$}
  \usepackage{setspace}
  \usepackage[modulo]{lineno}
mainfont: Times New Roman
bibliography: solanum-kinetics.bib
csl: https://www.zotero.org/styles/pnas
---

```{=latex}
\begin{center}
$^1$School of Life Sciences, University of Hawaiʻi; Mānoa, Hawaiʻi, USA\\
$^2$Department of Botany, University of Wisconsin, Madison; Wisconsin, USA\\
\medskip
*Corresponding author: cdmuir@wisc.edu\\
\medskip
ORCID: Christopher D. Muir — \href{https://orcid.org/0000-0003-2555-3878}{0000-0003-2555-3878}\\
\medskip
Classification: Biological Sciences, Ecology\\
\medskip
Keywords: amphistomy, leaf gas exchange, \textit{Solanum}, stomatal kinetics, stomatal size
\end{center}
```

```{r load-objects, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(brms)
library(cowplot)
library(dplyr)
library(ggplot2)
library(glue)
library(kableExtra)
library(knitr)
library(lubridate)
library(magrittr)
library(readr)
library(stringr)
library(tibble)
library(tidyr)

theme_set(theme_cowplot())

source("../r/functions.R")

```


## Abstract

Guard cell size and stomatal density vary over X and X orders of magnitude among extant vascular land plants, yet the adaptive significance of much of this variation remains unclear. The evolution of guard cell size in particular is poorly understood and may even be constrained by nonadaptive features like genome size. One hypothesis is that natural selection may favor smaller guard cells to increase the rate at which stomatal conductance responds to fluctuating environmental conditions. A related hypothesis is that operational stomatal conductance (gop) is often $\approx 25\%$ of its theoretical maximum (gmax) because at this stomatal aperture, guard cell volume is poised to change rapidly with changes in turgor pressure. The support for both hypothesis is limited and mixed, in part because they have not been tested together, even though both guard cell size and the ratio of gop to gmax (gop:gmax) should influence stomatal kinetics. We measured stomatal closure kinetics in response to an abrupt increase in vapor pressure deficit (VPD) among 29 diverse wild tomato populations in the genus \textit{Solanum}. Both smaller guard cell size and lower gop:gmax were associated with faster stomatal closure kinetics, but at different levels of biological organization. Guard cell size explained X% of the variance in stomatal kinetics among populations, whereas gop:gmax explained X% of the variance among individuals within populations. [neither result would have been supported if analyzed in isolation - is this true?]. We conclude that guard cell size may respond to selection on stomatal kinetics over evolutionary time, but actual kinetics are modulated by a tradeoff between maximizing gop and minimizing the time required for stomatal closure. Putting these hypotheses together with stabilizing selection on gop may explain why stomatal size and density negatively covary among species.

## Introduction

In nature, change is the only constant. One way that vascular plants (tracheophytes) cope with change is by adjusting stomatal pore aperture to optimize the trade-off between carbon gain and water loss. In the absence of physical limits and energentic tradeoffs, stomatal conductance (gsw) would respond instantaneously to perfectly track dynamic environmental conditions. In reality, stomatal responses take time. X ions must be pumped across ... and active responses depend on multiple feedback loops involving gene expression/ABA synthesis?/etc (Buckley). [illustrative empirical example or real numbers illustrating the problem]. Changes in stomatal aperture could be faster if there were more channels (?) per area, but this would require more energy (ATP?) and space in the guard cell membrane. 

At first it might seem that natural selection should always favor faster stomatal responses to get closer to the ideal of instantaneous optimization. However, once you account for time lags and tradeoffs, it is less clear that faster is always better. Review some lit...

There are two related hypotheses about how leaves might ... Two major hypotheses that are related but not well connected. One hypothesis is that smaller stomata are speedier. Explain why. Evidence is mixed. 

One factor that might complicate the relationship between size and speed is aperture. As gop approaches gmax, large changes in turbot are required to make small changes in a. Over the long-term, selection optimizes gop:gmax ratio (Franks et al. 2012). What's evidence or progress on this?


Is there a connection here to size-density scaling? It’s an empirical regularity, not a law of nature that higher gmax is associated with smaller stomata. This is an observation that requires explanation, not a presumption of truth. 

What's never been done before is to put these two ideas together. This means that weak relationships between size and speed might be because people have not controlled for aperture (gop:gmax ratio).

Factors cannot also manifest at different scales of biological organization. Here we focus on two levels: variation among species and variation among individuals within species. To consider it abstractly, if factors A and B influnce trait C according to some mechanistic model, but factor A is typically fixed within species but varies among species, then B will explain much of the variation in C within species. But if A varies among species, then A will explain much of the variation in C among species. We hypothesize that stomatal size is relatively constant within species, but varies among species.  In contrast, aperture (gop:gmax) varies because of mismatches between leaf anatomy and gopt.


And that smaller stomata are faster.

These are related because the benefit of small stomata goes away if gop is really high.



hooks:


Haworth et al (2018) paper arguing faster adaxial kinetics (I think). Check other cites in Woning and Horak




Stomatal kinetics are important for optimizing response to rapid fluctuations in light, leaf temperture, and VPD

curve shape does not match what you'd expect for constant alpha term

Anatomy possibly matters: shape and size

Adaxial stomata might close faster (why?)

What we did:\
1. model stomatal close with hysteresis (can it explain overshoot and wrong-way response?

2.  compare tau in tomatoes to that in rice
3.  test for effect of size
4.  test if adaxial+abaxial is faster than abaxial alone

CD WEibull in Woning et al

g_s = g_f + (g_i - g_f) * exp(-(t/tau)^lambda)

## Methods

lorem ipsum

## Results (writing on 2/6 that will be merged)

Stomatal conductance decrease rapidly in response to a sudden increase in VPD. The median time constant ($\tau) among wild tomato accessions was 






## MANUSCRAPS

Note: this theory did not really pan out. It did not come up with models that really fit better than the CD Weibull model and they included an extra parameter. Therefore, I am tabling this for now and trying OnGuard3 instead.

### Theory

Our goal here is derive equations that integrate the effects of guard cell size and aperture on stomatal kinetics. A fully mechanistic model is beyond the scope of our goals here. Instead, we use phenomenological equations that adequately capture empirical patterns. There are three main assumptions of our model. First, we assume linear relaxation kinetics for guard cell turgor pressure ($P$):

$$ \frac{d P}{d t} = \frac{P^* - P}{\tau}.$$
In this differential equation, $P^*$ is the equilibrium turgor pressure and $\tau$ is a time constant that determines the speed of relaxation. Solving this equation gives:

$$ P(t) = P^* + [P(0) - P^*] e^{-t/\tau}, $$
where $P(0)$ is the initial turgor pressure at time $t=0$.

The rate of relaxation is determined by the surface area to volume ratio. Assume constant transport per surface area. Surface area determined by geometry. 

What is eqn for this?



