---
title: Guard cell size and pore aperture influence stomatal closure kinetics
format:
  pdf:
    keep-tex: true  
    toc: false
author:
  - name: "Christopher D. Muir$^{1,2*}$"
    orcid: 0000-0003-2555-3878
  - name: "Wei Shen Lim$^{1}$"
affiliations: false
number-sections: false
header-includes: |
  \usepackage{hyperref}
  \addtokomafont{disposition}{\rmfamily}
  \usepackage{siunitx}
  \newcommand{\Aamphi}{$A_{\mathrm{amphi}}$}
  \newcommand{\Ahypo}{$A_{\mathrm{hypo}}$}
  \newcommand{\agcurve}{$A \textendash g_\text{sw}$}
  \newcommand{\ca}{$C_\mathrm{a}$}
  \newcommand{\caequals}[1]{$C_\mathrm{a} = \SI{#1}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\cabetween}[2]{#1 < $C_\mathrm{a} < \SI{#2}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\fgmax}{$f_\text{gmax}$}
  \newcommand{\gcl}{$l_\text{gc}$}
  \newcommand{\gmax}{$g_\text{max}$}
  \newcommand{\gmaxratio}{$g_\text{max,ratio}$}
  \newcommand{\gmaxshade}{$g_\text{max,shade}$}
  \newcommand{\gmaxsun}{$g_\text{max,sun}$}
  \newcommand{\gsw}{$g_\text{sw}$}
  \newcommand{\loggsw}{$\log(g_\text{sw})$}
  \newcommand{\logA}{$\log(A)$}
  \newcommand{\ppfd}{$\mathrm{PPFD}$}
  \newcommand{\ppfdequals}[1]{$\mathrm{PPFD} = \SI{#1}{\micro\mole\per\meter\squared\per\second}$}
  \newcommand{\ppfdqty}[1]{$\SI{#1}{\micro\mole\per\meter\squared\per\second}$}
  \newcommand{\rh}{$\mathrm{RH}$}
  \newcommand{\rhequals}[1]{$\mathrm{RH} = #1\%$}
  \newcommand{\tleafequals}[1]{$T_\mathrm{leaf} = \SI{#1}{\degreeCelsius}$}
  \usepackage{setspace}
  \usepackage[modulo]{lineno}
  \usepackage{physics}
  \usepackage{pifont}
  \newcommand{\cmark}{\ding{51}}
mainfont: Times New Roman
bibliography: solanum-kinetics.bib
csl: https://www.zotero.org/styles/pnas
---

```{=latex}
\begin{center}
$^1$School of Life Sciences, University of Hawaiʻi; Mānoa, Hawaiʻi, USA\\
$^2$Department of Botany, University of Wisconsin, Madison; Wisconsin, USA\\
\medskip
*Corresponding author: cdmuir@wisc.edu\\
\medskip
ORCID: Christopher D. Muir — \href{https://orcid.org/0000-0003-2555-3878}{0000-0003-2555-3878}\\
\medskip
Classification: Biological Sciences, Ecology\\
\medskip
Keywords: amphistomy, leaf gas exchange, \textit{Solanum}, stomatal kinetics, stomatal size
\end{center}
```

```{r load-objects, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(brms)
library(cowplot)
library(dplyr)
library(ggplot2)
library(glue)
library(kableExtra)
library(knitr)
library(lubridate)
library(magrittr)
library(readr)
library(stringr)
library(tibble)
library(tidyr)

theme_set(theme_cowplot())

source("../r/functions.R")

# Results
fit = read_rds("../objects/best_model.rds")

n_acc = length(unique(fit$data$accession))

# Effect of growth light treatment on log(tau)
post_summary = posterior_summary(fit)
post_tau_sun = post_summary["b_logtaumean_lighttreatmentsun", ]
post_tau_high = post_summary["b_logtaumean_lightintensityhigh", ]
post_lambda_sun = post_summary["b_loglambdamean_lighttreatmentsun", ]
post_lambda_high = post_summary["b_loglambdamean_lightintensityhigh", ]

tab_estimates = read_csv("../tables/tab-estimates.csv", show_col_types = FALSE)

median_tau = tab_estimates |>
  filter(trait == "tau") |>
  pull(estimate) |>
  median()

max_tau = tab_estimates |>
  filter(trait == "tau") |>
  pull(estimate) |>
  max()

median_lambda = tab_estimates |>
  filter(trait == "lambda") |>
  pull(estimate) |>
  median()

max_lambda = tab_estimates |>
  filter(trait == "lambda") |>
  pull(estimate) |>
  max()

```

blah [@tbl-foo]

```{r, foo}
#| label: tbl-foo
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(dplyr)
library(knitr)
library(kableExtra)


fit = read_rds("../objects/best_model.rds")
  
df1 = fit$data |>
  summarize(
    n = n(),
    .by = c(lightintensity, lighttreatment, curve_type)
  ) |>
  pivot_wider(
    names_from = c(lightintensity, curve_type),
    values_from = n
  ) |>
  # add row totals
  mutate(Total = rowSums(across(where(is.numeric)))) 

df2 = df1 |>
  bind_rows(
    df1 |>
      summarise(
        lighttreatment = "Total",
        across(where(is.numeric), \(.x) sum(.x, na.rm = TRUE))
      )
  ) |>
  mutate(across(where(is.numeric), \(.x) prettyNum(.x, big.mark = ","))) |>
  select(lighttreatment, low_amphi, low_pseudohypo, high_amphi, high_pseudohypo, Total)

kable(
  df2,
  format = "latex",
  booktabs = TRUE,
  align = "lccccc",
  escape = FALSE,
  col.names = c(
    "Growth light intensity",
    "amphi",
    "pseudohypo",
    "amphi",
    "pseudohypo",
    "Total"
  )) |>
  add_header_above(c(
    " " = 1,
    "Low" = 2,
    "High" = 2,
    " " = 1
  )) |>
  add_header_above(c(
    " " = 1,
    "Measurement light intensity" = 4,
    " " = 1
  )) |>
  row_spec(2, hline_after = TRUE)

```
